### ISSUE TITLE
example trouble: Single-mixed refrigerant (SMR) natural gas liquefaction process simulation optimization

### ISSUE THREAD

**Issue by tatsuya-takakuwa** [lf-santos/pyDWSIMopt#8]
Thank you for developing greatful tools!
I've been following the given examples verbatim, but I've encountered an issue as described below. It seems that the 'dof' argument is not being recognized. Are there any potential reasons for this you could think of?
I appreciate your assistance.

```
# Getting DWSIM path from system path
path2dwsim = []
for k,v in enumerate(os.environ['path'].split(';')):
    if v.find('\DWSIM')>-1:
        path2dwsim = os.path.join(v, '')
if path2dwsim == None:
    path2dwsim = "my_path"

# Loading DWSIM simulation into Python (Simulation object)
#sim_smr = SimulationOptimization(path2sim= os.path.join(dir_path, "examples\\SMR_LNG\\SMR.dwxmz"), 
#                     path2dwsim = path2dwsim)
sim_smr = SimulationOptimization(dof=np.array([]), path2sim= os.path.join(dir_path, "examples\\SMR_LNG\\SMR.dwxmz"), 
                     path2dwsim = path2dwsim)
sim_smr.savepath = os.path.join(dir_path, "examples\\SMR_LNG\\SMR2.dwxmz")
sim_smr.add_refs()
I 
```
**TypeError: __init__() got an unexpected keyword argument 'dof'``**

**Comment by lf-santos** [comment]
Hi @tatsuya-takakuwa 

Thanks for raising this issue.

Could you tell me what version of `dwsimopt` you are using? If you are using version >= 0.2.0, I would highly recommend the new class `OptimiSim` as instructed in [examples/example_v0.2.ipynb](https://github.com/lf-santos/dwsimopt/blob/master/examples/example_v0.2.ipynb). Please let me know if that solves your issue.

Kind regards,
Lucas.
